name: Update

on:
  schedule:
    - cron: "0 0 * * *"  # Exécution chaque jour à minuit UTC
  workflow_dispatch:  # Permet d'exécuter manuellement le workflow

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          
      - name: Install dependencies (si nécessaire)
        run: |
          python -m pip install --upgrade pip

      - name: Run the script to update README
        run: python utils/days.py

      - name: Commit and push changes
        run: |
          git config --global user.name "Matthieu Gillieron"
          git config --global user.email "action@github.com"
          git add README.md
          git commit -m "Reality Shift"
          git push https://github.com/MatthieuGillieron/MatthieuGillieron.git HEAD:main
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
